version: 2.1

orbs:
  common: vidsy/common@volatile
  services: vidsy/services@volatile

ignore-master: &ignore-master
  filters:
    branches:
      ignore: master

require-install: &require-install
  requires:
    - go/install

tagged-build: &tagged-build
  tags:
    only: /[0-9]+\.[0-9]+\.[0-9]+/

working-directory: &working-directory
  working-directory: /go-base

jobs:
  build-image:
    working_directory: /go-base
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: apk update && apk add make
      - run:  make build-image
  deploy:
    working_directory: /go-base
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: apk update && apk add make
      - run: make build-image
      - run: make push-to-registry -e CIRCLE_TAG=$CIRCLE_TAG

workflows:
  build-test-deploy:
    jobs:
      - common/check-for-clubhouse-ticket-comment:
          context: org-github-docker-hub
          <<: *ignore-master
      - common/check-version:
          <<: *ignore-master
      - build-image:
          <<: *ignore-master
      - deploy:
          context: org-go-services
          requires:
            - build-image
          filters:
            <<: *tagged-build
            branches:
              ignore: /.*/

